name: docblock_update

on:
  pull_request:
    branches: [ "*" ]

jobs:
  update-docblocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}

      - name: Update docblocks
        run: |
          SOURCE_URL=$(jq -r '.support.source' composer.json)
          docker run -v ./src:/app/run --rm davidsmith3/docblock-annotator-cli \
            docblock-annotator-cli:update-directory /app/run "@link $SOURCE_URL"

      - name: Commit and push changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Update docblocks with @link annotations"
            git push
          else
            echo "No changes to commit."
          fi
