name: docblock_update

on:
  pull_request:
    branches: [ "*" ]

permissions:
  pull-requests: read

jobs:
  update-docblocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Update docblocks
        run: |
          SOURCE_URL=$(jq -r '.support.source' composer.json)
          docker run -v ./src:/app/run --rm davidsmith3/docblock-annotator-cli \
            docblock-annotator-cli:update-directory /app/run "@link $SOURCE_URL"

      - name: Commit and push changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Update docblocks with @link annotations"
            git push
          else
            echo "No changes to commit."
          fi
