name: docblock_update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-docblocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract source URL from composer.json
        id: get-source-url
        run: |
          SOURCE_URL=$(jq -r '.support.source' composer.json)
          echo "source_url=$SOURCE_URL" >> $GITHUB_OUTPUT

      - name: Run Docblock Annotator
        run: docker run -v ./src:/app/run --rm davidsmith3/docblock-annotator-cli docblock-annotator-cli:update-directory /app/run "@link {${{ steps.get-source-url.outputs.source_url }}}"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Update docblocks with @link annotations"
          
      - name: Push changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git push origin HEAD:${{ github.head_ref }}
          else
            git push origin HEAD:${{ github.ref_name }}
          fi